version: "3"

services:
  postgres:
    container_name: quizarus_postgres
    image: postgres:14.2-alpine
    build:
      args:
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/db-setup.sql:/docker-entrypoint-initdb.d/db-setup.sql
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"


  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ACCESS_KEY=$S3_ACCESS_KEY
      - MINIO_SECRET_KEY=$S3_SECRET_KEY
    volumes:
      - minio-data:/data
    command: server /minio-data --console-address ":9090"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set miniorun http://minio:9000 $S3_ACCESS_KEY $S3_SECRET_KEY;
      /usr/bin/mc mb miniorun/$S3_PUBLIC_BUCKET;
      /usr/bin/mc mb miniorun/$S3_BUCKET;
      /usr/bin/mc anonymous set download miniorun/$S3_PUBLIC_BUCKET;
      exit 0;
      "

volumes:
  postgres-data:
  minio-data:
