"""added abstract model, question model

Revision ID: 43b4e70a4c45
Revises: 82e4427882b7
Create Date: 2023-05-07 22:48:39.495026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b4e70a4c45'
down_revision = '82e4427882b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('question_pack', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('question_pack', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_pack', 'updated_at')
    op.drop_column('question_pack', 'created_at')
    op.drop_table('question')
    # ### end Alembic commands ###
