"""added relation question -> pack

Revision ID: 78052010215a
Revises: 43b4e70a4c45
Create Date: 2023-05-07 22:53:13.040988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78052010215a'
down_revision = '43b4e70a4c45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('pack_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'question', 'question_pack', ['pack_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'pack_id')
    # ### end Alembic commands ###
