"""add pack description

Revision ID: 82e4427882b7
Revises: 3469b7675046
Create Date: 2023-05-07 22:20:36.469500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e4427882b7'
down_revision = '3469b7675046'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_pack', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('question_pack', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_question_pack_id', table_name='question_pack')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_question_pack_id', 'question_pack', ['id'], unique=False)
    op.alter_column('question_pack', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('question_pack', 'description')
    # ### end Alembic commands ###
